version: "3.9"
services:

  pgsql:
    image: postgres:13.2-alpine
    expose: 
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: devenv
      POSTGRES_DB: loginsrv_dev
    volumes:
      - db-data:/var/lib/postgresql/data

  db:
    build: 
      context: ./db
      dockerfile: Dockerfile.liquibase
    depends_on: [ 'pgsql' ]
    volumes:
      - ./db:/liquibase/changelog
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: devenv
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_NAME: loginsrv_dev
    command: update 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PGHOST: pgsql
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: devenv
      PGDATABASE: loginsrv_dev
    volumes:
      - ./backend:/loginsrv/backend 

volumes:
  db-data:
